[package]
name = "gcp-access-token"
version = "0.3.0"
authors = ["Yong Wen Chua <lawliet89@users.noreply.github.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
failure = "0.1.7"
serde_json = "1.0"
tokio = { version = "0.2.16", features = ["macros"] }
yup-oauth2 = "4.1.0"
